export const BUILTIN_CATEGORY_RULES: Record<string, string> = {
  bus: "Transport",
  mrt: "Transport",
  grab: "Transport",
  ntuc: "Groceries",
  fairprice: "Groceries",
  giant: "Groceries",
  "cold storage": "Groceries",
  "sheng siong": "Groceries",
  market: "Groceries",
  supermarket: "Groceries",
  koufu: "Food",
  "burger king": "Food",
  shihlin: "Food",
  mala: "Food",
  "soup spoon": "Food",
  "don don donki": "Food",
  chicha: "Food",
  "7-eleven": "Food",
  bakery: "Food",
  "chicken rice": "Food",
  ijooz: "Food",
  interest: "Interest",
  shopee: "Shopping",
  popular: "Shopping",
  usmobile: "Bills",
};

export const USER_CATEGORY_RULES: Record<string, string> = {
  "7 eleven": "Groceries",
  "forecoffeepteltdn asg": "Food",
  "fr313fitrachickenricesingaporesg": "Food",
  "gojek": "Transport",
  "liho": "Food",
  "moomoosg customers account": "Investment",
  "nando s": "Food",
  "pizza hut": "Food",
  "subway": "Food",
  "sushiro thomsonplazasingaporesg": "Food",
  "synapxe pteltd co mohh": "Income",
  "synapxepteltd co mohh": "Income",
  "synapxepteltdcomohh": "Income",
};
